
export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS_EXITO'

export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO'

export const CONFIRMAR_ORDENAR_PLATILLO = 'CONFIRMAR_ORDENAR_PLATILLO'

export const TOTAL_A_PAGAR = 'TOTAL_A_PAGAR'

export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO'

export const PEDIDO_ORDENADO = 'PEDIDO_ORDENADO'